services:
  redis:
    image: redis:latest
    container_name: takeout_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  app:
    build: .
    container_name: takeout_app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    env_file:
      - config.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: on-failure

volumes:
  postgres_data:
  redis_data: