services:
  redis:
    image: redis:latest
    container_name: takeout_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  postgres:
    image: ankane/pgvector:latest
    container_name: takeout_postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build: .
    container_name: takeout_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    env_file:
      - config.env
      - .env
    restart: on-failure

volumes:
  postgres_data:
  redis_data: